"""add colum of ticket_id in epaas,complint

Revision ID: 28acbec87284
Revises: e4e2d49b23e9
Create Date: 2026-01-29 16:26:00.614437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28acbec87284'
down_revision: Union[str, Sequence[str], None] = 'e4e2d49b23e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logs_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('logs_id')
    )
    op.add_column('complaint', sa.Column('ticket_id', sa.Integer()))
    op.add_column('complaint', sa.Column('status', sa.String(), nullable=True))
    op.add_column('complaint', sa.Column('remark', sa.String(), nullable=True))
    op.drop_index(op.f('ix_complaint_complaint_id'), table_name='complaint')
    op.create_index(op.f('ix_complaint_ticket_id'), 'complaint', ['ticket_id'], unique=False)
    op.drop_column('complaint', 'complaint_id')
    op.drop_column('complaint', 'action')
    op.add_column('epass', sa.Column('ticket_id', sa.Integer()))
    op.drop_constraint(op.f('epass_request_id_key'), 'epass', type_='unique')
    op.create_index(op.f('ix_epass_ticket_id'), 'epass', ['ticket_id'], unique=False)
    op.drop_column('epass', 'request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epass', sa.Column('request_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_epass_ticket_id'), table_name='epass')
    op.create_unique_constraint(op.f('epass_request_id_key'), 'epass', ['request_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('epass', 'ticket_id')
    op.add_column('complaint', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('complaint', sa.Column('complaint_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_complaint_ticket_id'), table_name='complaint')
    op.create_index(op.f('ix_complaint_complaint_id'), 'complaint', ['complaint_id'], unique=False)
    op.drop_column('complaint', 'remark')
    op.drop_column('complaint', 'status')
    op.drop_column('complaint', 'ticket_id')
    op.drop_table('user_logs')
    # ### end Alembic commands ###
