"""table update

Revision ID: 34ec4409bb34
Revises: e4a4f5e231a4
Create Date: 2026-01-28 09:37:12.129925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ec4409bb34'
down_revision: Union[str, Sequence[str], None] = 'e4a4f5e231a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profile',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('resident',
    sa.Column('house_no', sa.String(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner')
    )
    op.create_table('vehicle',
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner', 'number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('resident')
    op.drop_table('profile')
    op.drop_table('auth')
    # ### end Alembic commands ###
