"""fix index

Revision ID: 584c2bc52516
Revises: 7f3fe2641c2a
Create Date: 2026-01-29 17:14:59.378183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584c2bc52516'
down_revision: Union[str, Sequence[str], None] = '7f3fe2641c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('ticket_id', sa.Integer(), sa.Identity(always=False, start=201, increment=1), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('attachment', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_complaint_ticket_id'), 'complaint', ['ticket_id'], unique=False)
    op.create_table('epass',
    sa.Column('ticket_id', sa.Integer(), sa.Identity(always=False, start=101, increment=1), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('guest_name', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('arrival', sa.String(), nullable=True),
    sa.Column('departure', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('vehicle_no', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_epass_ticket_id'), 'epass', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epass_ticket_id'), table_name='epass')
    op.drop_table('epass')
    op.drop_index(op.f('ix_complaint_ticket_id'), table_name='complaint')
    op.drop_table('complaint')
    # ### end Alembic commands ###
