"""first

Revision ID: 8d7e8876287a
Revises: 
Create Date: 2026-01-29 08:37:20.109152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7e8876287a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('complaint',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('attachement', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index(op.f('ix_complaint_complaint_id'), 'complaint', ['complaint_id'], unique=False)
    op.create_table('epass',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('arrival', sa.String(), nullable=True),
    sa.Column('departure', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('vehicle_no', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('personal',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('resident',
    sa.Column('house_no', sa.String(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner')
    )
    op.create_table('token',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('vehicle',
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner', 'number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('token')
    op.drop_table('resident')
    op.drop_table('personal')
    op.drop_table('epass')
    op.drop_index(op.f('ix_complaint_complaint_id'), table_name='complaint')
    op.drop_table('complaint')
    op.drop_table('auth')
    # ### end Alembic commands ###
