"""add complaint table

Revision ID: 8dd29685892b
Revises: cdbdd5b4fcd9
Create Date: 2026-01-28 12:25:32.844323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dd29685892b'
down_revision: Union[str, Sequence[str], None] = 'cdbdd5b4fcd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('attachement', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index(op.f('ix_complaint_complaint_id'), 'complaint', ['complaint_id'], unique=False)
    op.create_table('personal',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('profile')
    op.create_unique_constraint(None, 'auth', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='unique')
    op.create_table('profile',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], name=op.f('profile_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('profile_pkey'))
    )
    op.drop_table('personal')
    op.drop_index(op.f('ix_complaint_complaint_id'), table_name='complaint')
    op.drop_table('complaint')
    # ### end Alembic commands ###
