"""create resident table

Revision ID: 9e82ca90d138
Revises: 
Create Date: 2026-01-28 06:57:50.550975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e82ca90d138'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('auth', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('auth', 'id')
    op.add_column('profile', sa.Column('Name', sa.String(), nullable=False))
    op.alter_column('profile', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('fkey_user_id'), 'profile', type_='foreignkey')
    op.create_foreign_key(None, 'profile', 'auth', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('profile', 'name')
    op.alter_column('resident', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resident', 'pincode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('fey_owner'), 'resident', type_='foreignkey')
    op.create_foreign_key(None, 'resident', 'auth', ['owner'], ['user_id'], ondelete='CASCADE')
    op.add_column('vehicle', sa.Column('number', sa.String(), nullable=False))
    op.drop_column('vehicle', 'vehicle_no')
    op.drop_column('vehicle', 'vehicle_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('vehicle_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('vehicle_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('vehicle', 'number')
    op.drop_constraint(None, 'resident', type_='foreignkey')
    op.create_foreign_key(op.f('fey_owner'), 'resident', 'auth', ['owner'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('resident', 'pincode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('resident', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('profile', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.create_foreign_key(op.f('fkey_user_id'), 'profile', 'auth', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('profile', 'timestamp',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('profile', 'Name')
    op.add_column('auth', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('auth', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('auth', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
