"""second revison of some typo mistake

Revision ID: e4e2d49b23e9
Revises: 8d7e8876287a
Create Date: 2026-01-29 10:21:16.414844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e2d49b23e9'
down_revision: Union[str, Sequence[str], None] = '8d7e8876287a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth', ['user_id'])
    op.add_column('complaint', sa.Column('attachment', sa.String(), nullable=True))
    op.drop_column('complaint', 'attachement')
    op.create_unique_constraint(None, 'epass', ['request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'epass', type_='unique')
    op.add_column('complaint', sa.Column('attachement', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('complaint', 'attachment')
    op.drop_constraint(None, 'auth', type_='unique')
    # ### end Alembic commands ###
