"""add notice table

Revision ID: 4109892306c4
Revises: becf3bf0328b
Create Date: 2026-01-31 17:15:43.952615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4109892306c4'
down_revision: Union[str, Sequence[str], None] = 'becf3bf0328b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('notice_id', sa.Integer(), sa.Identity(always=False, start=1001, increment=1), nullable=False),
    sa.Column('Type', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('notice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notices')
    # ### end Alembic commands ###
