"""add role column in auth table 

Revision ID: 80b5263981f8
Revises: 4109892306c4
Create Date: 2026-01-31 18:50:56.093420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b5263981f8'
down_revision: Union[str, Sequence[str], None] = '4109892306c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('role', sa.String(), server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'role')
    # ### end Alembic commands ###
