"""remove Foreign key from token user_id with auth

Revision ID: becf3bf0328b
Revises: 0978d9a288e4
Create Date: 2026-01-31 12:37:17.130939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becf3bf0328b'
down_revision: Union[str, Sequence[str], None] = '0978d9a288e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth', ['user_id'])
    op.drop_constraint(op.f('token_user_id_fkey'), 'token', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('token_user_id_fkey'), 'token', 'auth', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'auth', type_='unique')
    # ### end Alembic commands ###
